ALTER TYPE "FeedbackValue" RENAME VALUE 'UP' TO 'HELPFUL';
ALTER TYPE "FeedbackValue" RENAME VALUE 'DOWN' TO 'MISSED_POINT';
ALTER TYPE "FeedbackValue" ADD VALUE 'INTERESTING';
ALTER TYPE "FeedbackValue" ADD VALUE 'FUNNY';
ALTER TYPE "FeedbackValue" ADD VALUE 'PUSH_BACK_MORE';
ALTER TYPE "FeedbackValue" ADD VALUE 'GO_DEEPER';
ALTER TYPE "FeedbackValue" ADD VALUE 'TOO_MUCH';
ALTER TYPE "FeedbackValue" ADD VALUE 'TOO_META';
